### ISSUE TITLE
Why does the inline assembly use `pure,nomem`?

### ISSUE THREAD

**Issue by daira** [cesarb/constant_time_eq#8]
These are [documented](https://doc.rust-lang.org/reference/inline-assembly.html#options) as follows:

> *pure*: The `asm!` block has no side effects, and its outputs depend only on its direct inputs (i.e. the values themselves, not what they point to) or values read from memory (unless the *nomem* options is also set). This allows the compiler to execute the `asm!` block fewer times than specified in the program (e.g. by hoisting it out of a loop) or even eliminate it entirely if the outputs are not used.
>
> *nomem*: The `asm!` blocks does not read or write to any memory. This allows the compiler to cache the values of modified global variables in registers across the `asm!` block since it knows that they are not read or written to by the `asm!`.

Don't these just make it much easier for a future potential version of the Rust compiler to conclude that the assembly can be optimised out? Why are they necessary?

**Comment by sugar700** [comment]
`pure` can only be removed if `asm!` outputs aren't used at all, which in practice will only happen if the result of functions in this crate will be completely ignored (say, if you do `let _ = constant_time_eq(a, b)`, then the compiler will be allowed to compile down to nothing).

It doesn't permit optimizations basing on `asm` block contents, the compiler cannot assume the `asm` block is an identity function (it is, but the compiler is not allowed to optimize basing on that). All that compiler knows is that an `asm` block is pure.

**Comment by cesarb** [comment]
> Don't these just make it much easier for a future potential version of the Rust compiler to conclude that the assembly can be optimised out?

As @xfix mentioned, they allow even current versions of the Rust compiler to conclude that the assembly can be optimized out whenever its output is not being used. That, in turn, allows the Rust compiler to optimize out the whole call to the `constant_time_eq` function whenever its result is not being used. They do not, however, allow any current or future version of the Rust compiler to optimize out the assembly (and the whole function) when its output is being used.

> Why are they necessary?

They prevent the inline assembly from interfering with unrelated optimizations. Without these four flags, the inline assembly would be a much stronger optimization barrier than is necessary here.

**Comment by daira** [comment]
Thanks for your answers!
